### ISSUE TITLE
Works for url to json, but not with file or string

### ISSUE THREAD

**Issue by jkitchin** [jmshea/jupytercards#2]
I have put flashcard definitions in a file called "flash.json". If I load that file from a URL the package works well. But, if I try any of these variants, it fails with `Javascript Error: Cannot read properties of null (reading 'dataset')`

    display_flashcards('flash.json'). # a file ref

    display_flashcards(open('flash.json').read()) # string of the json

    display_flashcards(json.loads(open('flash.json').read())). # list of dictionaries

it seems like all three should work.

**Comment by jmshea** [comment]
Yes, I'm seeing this, too now. It was working before, so let me track down what changed.

Thank you for letting me know!

**Comment by jmshea** [comment]
Please upgrade to the latest (1.9.9), which is in PyPI:

pip install --upgrade jupytercards

Hopefully, it is fixed. I merged a PR that had some fixes, but the contributor accidentally put the JavaScript stuff before the HTML, which caused this break.

**Comment by jkitchin** [comment]
That does seem to have fixed it. Thanks for the quick reply!
